### PR TITLE
Fix segfaults in some cases; streamlined part of the codes

### PR DESCRIPTION
**Pull request by FlyingWithJerome**
I had also added some test cases in regression test; they might be false positive since they failed in regression tests but I ran them directly from terminal and get the expected results from Panoply.

### CODE REVIEW

**Comment by czender** [comment]
Looks good. Just merged this. Jerome, please confirm that you understand that command line strings are owned by system memory not by NCO. Meaning that Bash (or whatever) allocates the memory that contains the command line. This system memory can be copied but should NEVER be modified by NCO. I'm wondering if the multi-argument routines attempt to modify system memory. This would cause segfaults...better to copy the system memory once and work on that.

**Comment by FlyingWithJerome** [comment]
Yes. Yesterday I read the code line by line, I found that I directly strcat two strings without reallocate new memory spaces...

**Comment by czender** [comment]
Good. However, all the new regression tests fail for me (on MacOS). Do they fail for you, too?

ncks    test 102: Add multiple global attributes with argument parsing by Jerome.....................   ERR: FAILURE in ncks failure: Add multiple global attributes with argument parsing by Jerome
   ERR::EXPLAIN: Result: [Thu Sep 15] != Expected: [Thu Sep 15 13:03:18 PDT 2016]

ncks    test 103: More tests on multi-argument parsing #1............................................   ERR: FAILURE in ncks failure: More tests on multi-argument parsing #1
   ERR::EXPLAIN: Result: [bar3] != Expected: [bar1]

ncks    test 104: More tests on multi-argument parsing #2(with time string).......................... !!FAILED
  $cmd_rsl_is_nbr = 1 and $xpc_is_nbr = 0
   ERR: FAILURE in ncks failure: More tests on multi-argument parsing #2(with time string)
   ERR::EXPLAIN: Result: [] != Expected: [Thu Sep 15 13:03:18 PDT 2016]

ncks    test 105: More tests on multi-argument parsing #3(the time string is followed by kvms)....... !!FAILED
  $cmd_rsl_is_nbr = 1 and $xpc_is_nbr = 0
   ERR: FAILURE in ncks failure: More tests on multi-argument parsing #3(the time string is followed by kvms)
   ERR::EXPLAIN: Result: [] != Expected: [bar10]

ncks    test 106: More tests on multi-argument parsing #4(all have subdelimiters).................... !!FAILED
  $cmd_rsl_is_nbr = 1 and $xpc_is_nbr = 0
   ERR: FAILURE in ncks failure: More tests on multi-argument parsing #4(all have subdelimiters)
   ERR::EXPLAIN: Result: [] != Expected: [Thu Sep 15 13:03:18 PDT 2016]

**Comment by FlyingWithJerome** [comment]
Yes, they failed on my Mac as well. But I had just manually checked each of them with Panoply and ncks. These commands all performed normally. Keys and values are exactly matched, and none is missing.

**Comment by czender** [comment]
so this is the "false positive" you mentioned. does this imply that running from Perl (in the regression test) yields different results than running from the command line. If so, I may be able to help.

**Pull request merged**
