### PR TITLE
Hmb gen msh5 nm

### PR DESCRIPTION
**Pull request by hmb1**
@czender 
latest and greatest interpolation method
big tidy up

### CODE REVIEW

**Comment by czender** [comment]
I am excited to see this merged! Please do so after you fix these compiler warnings in the PR.
```
nco_map.c: In function ‘nco_msh_mk’:
nco_map.c:1010:23: warning: format ‘%d’ expects argument of type ‘int’, but argument 4 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
       fprintf(stderr, "%s: INFO: num input polygons=%d, num output polygons=%d num overlap polygons=%d\n", nco_prg_nm_get(),grd_sz_in, grd_sz_out , pl_cnt_vrl);
                       ^
nco_map.c:1010:23: warning: format ‘%d’ expects argument of type ‘int’, but argument 5 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
nco_ply_lst.c: In function ‘nco_poly_lst_mk_sph’:
nco_ply_lst.c:400:27: warning: format ‘%d’ expects argument of type ‘int’, but argument 6 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
     (void)fprintf(stderr, "%s: %s size input list(%lu), size output list(%d)  total area=%.15e  num wrapped= %d num caps=%d num masked=%d\n", nco_prg_nm_get(),fnc_nm, grd_sz, grd_sz, tot_area, wrp_cnt, wrp_y_cnt, msk_cnt);
  
nco_sph.c:1882:12: warning: ‘LON_MAX_RAD’ is static but used in inline function ‘Cos’ which is not static
     theta-=LON_MAX_RAD;
            ^
nco_sph.c:1881:31: warning: ‘LON_MIN_RAD’ is static but used in inline function ‘Cos’ which is not static
   if(blon &&  theta > M_PI && LON_MIN_RAD >=0.0 )
                               ^
nco_sph.c:1850:14: warning: ‘LON_MAX_RAD’ is static but used in inline function ‘Sin’ which is not static
       theta-=LON_MAX_RAD;
              ^
nco_sph.c:1849:33: warning: ‘LON_MIN_RAD’ is static but used in inline function ‘Sin’ which is not static
     if(blon &&  theta > M_PI && LON_MIN_RAD >=0.0 )

nco_kd.c:2079:37: warning: address of array 'list[i].elem->size' will always
      evaluate to 'true' [-Wpointer-bool-conversion]
          if(list[i].elem && list[i].elem->size)
                          ~~ ~~~~~~~~~~~~~~^~~~

nco_map.c:1399:10: warning: enumeration value 'nco_grd_lon_nil' not handled in
      switch [-Wswitch]
  switch(typ_in){
         ^
```

**Comment by hmb1** [comment]
@czender 
thing I got most of the compiler warnings !!

**Comment by hmb1** [comment]
@czender 
go ahead and merge

**Comment by czender** [comment]
Thanks, merged!

**Pull request merged**
