### PR TITLE
Building of .deb

### PR DESCRIPTION
**Pull request by rkouznetsov**
Made  " dpkg-buildpackage -b -rfakeroot -us -uc" pass

Added dummy ChangeLog NEWS README
Fixed path in debian/rules
Fixed wrong date from future

### CODE REVIEW

**Comment by czender** [comment]
Thank you for your PR. We love PRs from new contributors! However, I dislike placing dummy NEWS README ChangeLog in top-level directory when those are all already in docs directory. It would be preferable to point dpkg-buildpackage to that directory for those files. Can you do this? If not, then please move the files from doc to top-level so we do not duplicate them which would be confusing.

**Comment by rkouznetsov** [comment]
Thank you! I agree that it is a dirty workaround to make dpkg-buildpackage pass. It looks like there is an issue with working directory when automake (or make?) tries to access the files it is in $(top_srcdir) while should be in $(top_srcdir)/doc...  
Unfortunately, my ignorance about the building mechanisms  did not let me to find the right place to correct this.

Moving the files to one level up, as you suggested does not help, since  dh_installchangelogs wants the changelog still in doc/.

In any case I have made a commit with moved files, despite "dpkg-buildpackage -b -rfakeroot -us -uc" fails on that commit.

**Comment by rkouznetsov** [comment]
Looks like Changelog has been updated in upstream. I could not find a way to merge this on my side..

**Comment by rkouznetsov** [comment]
Ok. Now I have got it working. Here is the line form configure.ac
`cd ~/nco;for fl in NEWS README AUTHORS ChangeLog ; do ln -s doc/${fl} ${fl};done;autoreconf --force`

After symlinking the files to the top-level directory `dpkg-buildpackage -b -rfakeroot -us -uc` passes.

**Pull request merged**
