### PR TITLE
Hmb dep ncap

### PR DESCRIPTION
**Pull request by hmb1**
Hi Charlie,
  please review mods at your leisure

Hi Pedro - 
Please double check that branch works on Windows (it works on AppVeyor)

### CODE REVIEW

**Comment by pedro-vicente** [comment]
builds, only a few warnings left


```
Invoke.cc
  cl /c /I"E:\nco\cmake\build\netcdf-c\include" /I"E:\nco\cmake\build\UDUNITS-2\lib" /IE:\nco\cmake\build\gsl\build /IE:\nco\src\nco /IE:\nco\cmake\build\antlr
  2\lib\cpp /Zi /W3 /WX- /Od /Ob0 /D WIN32 /D _WINDOWS /D ENABLE_STATIC /D HAVE_NC_INQ_PATH /D HAVE_NC_INQ_FORMAT /D HAVE_NC_DEF_VAR_FILTER /D HAVE_NC_INQ_VAR_
  FILTER /D NC_LIB_VERSION=460 /D HAVE_NETCDF_MEM_H /D _MATH_DEFINES_DEFINED /D HAVE_NETCDF4_H /D ENABLE_NETCDF4 /D ENABLE_UDUNITS /D HAVE_UDUNITS2_H /D ENABLE
  _GSL /D ENABLE_DAP /D ENABLE_DEBUG_SYMBOLS /D USER=pedro /D "HOSTNAME=DESKTOP-039C73K" /D NCO_BUILDENGINE=CMake /D _CRT_SECURE_NO_WARNINGS /D _CRT_NONSTDC_NO
  _DEPRECATE /D NEED_STRNCASECMP /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"ncap2.d
  ir\Debug\\" /Fd"ncap2.dir\Debug\vc140.pdb" /Gd /TP /wd4267 /wd4244 /wd4477 /errorReport:queue E:\nco\src\nco++\Invoke.cc E:\nco\src\nco++\NcapVar.cc E:\nco\s
  rc\nco++\NcapVarVector.cc E:\nco\src\nco++\fmc_all_cls.cc E:\nco\src\nco++\fmc_cls.cc E:\nco\src\nco++\fmc_gsl_cls.cc E:\nco\src\nco++\ncap2.cc E:\nco\src\nc
  o++\ncap2_att.cc E:\nco\src\nco++\ncap2_utl.cc E:\nco\src\nco++\ncoLexer.cpp E:\nco\src\nco++\ncoParser.cpp E:\nco\src\nco++\ncoTree.cpp E:\nco\src\nco++\prs
  _cls.cc

  NcapVar.cc
  NcapVarVector.cc
  fmc_all_cls.cc
E:\nco\src\nco++\fmc_all_cls.cc(2002): warning C4305: '*=': truncation from 'double' to 'float' [E:\nco\cmake\build\ncap2.vcxproj]
E:\nco\src\nco++\fmc_all_cls.cc(2727): warning C4800: 'int': forcing value to bool 'true' or 'false' (performance warning) [E:\nco\cmake\build\ncap2.vcxproj]
  fmc_cls.cc
  fmc_gsl_cls.cc
  ncap2.cc
E:\nco\src\nco++\ncap2.cc(759): warning C4800: 'int': forcing value to bool 'true' or 'false' (performance warning) [E:\nco\cmake\build\ncap2.vcxproj]
E:\nco\src\nco++\ncap2.cc(760): warning C4800: 'int': forcing value to bool 'true' or 'false' (performance warning) [E:\nco\cmake\build\ncap2.vcxproj]
E:\nco\src\nco++\ncap2.cc(761): warning C4800: 'int': forcing value to bool 'true' or 'false' (performance warning) [E:\nco\cmake\build\ncap2.vcxproj]
E:\nco\src\nco++\ncap2.cc(1183): warning C4101: 'dnan': unreferenced local variable [E:\nco\cmake\build\ncap2.vcxproj]
  ncap2_att.cc
  ncap2_utl.cc
  ncoLexer.cpp
  ncoParser.cpp
  ncoTree.cpp
ncoTree.cpp(1382): warning C4101: 'pe': unreferenced local variable [E:\nco\cmake\build\ncap2.vcxproj]
ncoTree.cpp(1427): warning C4101: 'pe': unreferenced local variable [E:\nco\cmake\build\ncap2.vcxproj]
ncoTree.cpp(1477): warning C4101: 'pe': unreferenced local variable [E:\nco\cmake\build\ncap2.vcxproj]
ncoTree.cpp(1535): warning C4101: 'pe': unreferenced local variable [E:\nco\cmake\build\ncap2.vcxproj]
ncoTree.cpp(1593): warning C4101: 'pe': unreferenced local variable [E:\nco\cmake\build\ncap2.vcxproj]
ncoTree.cpp(1651): warning C4101: 'pe': unreferenced local variable [E:\nco\cmake\build\ncap2.vcxproj]
ncoTree.cpp(1815): warning C4101: 'pe': unreferenced local variable [E:\nco\cmake\build\ncap2.vcxproj]
ncoTree.cpp(1869): warning C4101: 'pe': unreferenced local variable [E:\nco\cmake\build\ncap2.vcxproj]
ncoTree.cpp(1929): warning C4101: 'pe': unreferenced local variable [E:\nco\cmake\build\ncap2.vcxproj]
ncoTree.cpp(2007): warning C4101: 'pe': unreferenced local variable [E:\nco\cmake\build\ncap2.vcxproj]
ncoTree.cpp(2061): warning C4101: 'pe': unreferenced local variable [E:\nco\cmake\build\ncap2.vcxproj]
ncoTree.cpp(2121): warning C4101: 'pe': unreferenced local variable [E:\nco\cmake\build\ncap2.vcxproj]
ncoTree.cpp(2198): warning C4101: 'pe': unreferenced local variable [E:\nco\cmake\build\ncap2.vcxproj]
ncoTree.cpp(2252): warning C4101: 'pe': unreferenced local variable [E:\nco\cmake\build\ncap2.vcxproj]
ncoTree.cpp(2312): warning C4101: 'pe': unreferenced local variable [E:\nco\cmake\build\ncap2.vcxproj]
ncoTree.cpp(2389): warning C4101: 'pe': unreferenced local variable [E:\nco\cmake\build\ncap2.vcxproj]
ncoTree.cpp(2443): warning C4101: 'pe': unreferenced local variable [E:\nco\cmake\build\ncap2.vcxproj]
ncoTree.cpp(2503): warning C4101: 'pe': unreferenced local variable [E:\nco\cmake\build\ncap2.vcxproj]
ncoTree.cpp(2578): warning C4101: 'pe': unreferenced local variable [E:\nco\cmake\build\ncap2.vcxproj]
ncoTree.cpp(2632): warning C4101: 'pe': unreferenced local variable [E:\nco\cmake\build\ncap2.vcxproj]
ncoTree.cpp(2785): warning C4101: 'pe': unreferenced local variable [E:\nco\cmake\build\ncap2.vcxproj]
ncoTree.cpp(2853): warning C4101: 'pe': unreferenced local variable [E:\nco\cmake\build\ncap2.vcxproj]
ncoTree.cpp(3116): warning C4101: 'pe': unreferenced local variable [E:\nco\cmake\build\ncap2.vcxproj]
ncoTree.cpp(3210): warning C4101: 'pe': unreferenced local variable [E:\nco\cmake\build\ncap2.vcxproj]
ncoTree.cpp(3395): warning C4101: 'pe': unreferenced local variable [E:\nco\cmake\build\ncap2.vcxproj]
ncoTree.cpp(3457): warning C4101: 'pe': unreferenced local variable [E:\nco\cmake\build\ncap2.vcxproj]
ncoTree.cpp(3572): warning C4101: 'pe': unreferenced local variable [E:\nco\cmake\build\ncap2.vcxproj]
ncoTree.cpp(3831): warning C4101: 'pe': unreferenced local variable [E:\nco\cmake\build\ncap2.vcxproj]
ncoTree.cpp(4087): warning C4101: 'pe': unreferenced local variable [E:\nco\cmake\build\ncap2.vcxproj]
ncoTree.cpp(4283): warning C4101: 'pe': unreferenced local variable [E:\nco\cmake\build\ncap2.vcxproj]
  prs_cls.cc
  Generating Code...
e:\nco\src\nco++\fmc_gsl_cls.cc(5090): warning C4715: 'nco_gsl_cls::fnd': not all control paths return a value [E:\nco\cmake\build\ncap2.vcxproj]
```

**Comment by hmb1** [comment]
Thanks Pedro,
Ive already squelched most of the above compiler warnings in the "master" branch
THey will dispaear when I do the MR

**Comment by hmb1** [comment]
Hi Charlie,
Have merged ncap.h and ncap_yacc.h into the new file ncap_utl.h .
have deleted ncap_yacc.*  and  ncap.c and ncap.h  
All that remains to get it working on AppVeyor  and then delete the unused functions in ncap_utl.c
...Henry

**Comment by czender** [comment]
@hmb1 Sounds good, carry on. Once the checks pass and I know the new filenames then I will make the necessary changes to bld/Makefile and then we'll merge the patchset.

**Comment by czender** [comment]
What is the status of the failing appveyor check?

**Comment by hmb1** [comment]
attempt to resolve conflict in branch

**Comment by hmb1** [comment]
tidy up in ncap_lex.l and  ncap_utl.c

**Comment by hmb1** [comment]
Hi Pedro,
  thanks for doing the checks 
 I am having the same issue:
  
 And I cant find the links either

 ...Henry

On 27/02/2018 at 12:37 PM, "Pedro Vicente" <pedro.vicente@space-research.org> wrote:
Hi team

 
I’m trying to make some sense in GitHub about the supposed failures of #74

But cannot :=)

 Both branches compile for me locally
And I cannot see any appveyor log ; what would be the links to follow ?
-Pedro

**Comment by czender** [comment]
The PR box says :

> "This branch has conflicts that must be resolved
> to resolve conflicts before continuing.
> Conflicting files
> configure.ac
>  src/nco/ncap.c"

I would expect that after this is done manually, appveyor will test the merged sources.

**Comment by czender** [comment]
This is related to #74

**Comment by hmb1** [comment]
deleted following ncap_yacc.{c,h,y}
deleted ncap.c .
new file ncap_utl.c

**Pull request merged**
